### ISSUE TITLE
Migrate Bower dependency to NPM?

### ISSUE THREAD

**Issue by lougreenwood** [RSSchermer/ember-spin-spinner#6]
Hey there 😄 - Seems that the plugin needs to be migrated away from Bower to NPM.

Are there any plans for this?

Cheers!

**Comment by RSSchermer** [comment]
Hey!

You're right, this addon is quite out of date. I'll look into it, but it's a bit of a busy week, so it might take me a couple of days to get around to. Feel free to ping me in a week or so if I seem to have forgotten. Alternatively, a PR would of course also be very welcome :smile:

**Comment by RSSchermer** [comment]
Should be fixed as of 0.4.0
